Module7 task1
htmlacademy-ecmascript/1033161-big-trip-12 pull request #11
Opened 2020-09-10 14:20 UTC by cactusjam

2020-09-10 15:20 UTC, AlexMasterov requested changes

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/filter.js
> +    .reduce((res, el) => Object.assign(res, el), {});
`res`, `el`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/12/criteries#b4)
> Для названия значений используются английские существительные

> Сокращения в словах запрещены

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/point-new.js
> +  id: getRandomInteger(1, 4000),
`id` создается на сервере.

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/point-new.js
> +    const sortTripElement = this._container.querySelector(`.trip-sort`);
Д26~

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/point-new.js
> +  _handleDeletePointEdit() {
<details>
<summary>NewPointPresenter</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/presenter/point-new.js#L82-L84
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/presenter/point-new.js#L86-L88
</details>

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/trip.js
> +    const destinations = this._pointsModel.getDestinations();
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/presenter/trip.js#L62-L64

Зачем этот метод? 🤔

2020-09-10 15:20 UTC, AlexMasterov commented on src/utils/observer.js
> +export default class Observer {
Д3

2020-09-10 15:20 UTC, AlexMasterov commented on src/view/event-edit.js
> +      ${isAddMode ? `Cancel` : `Delete`}
`Cancel`
`Delete`

Б5~

2020-09-10 15:20 UTC, AlexMasterov commented on src/view/event-edit.js
> +const createEventEditTemplate = (data, destinations, isAddMode) => {
`data`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/12/criteries#b4)
> Использовать `data` для аргумента с данными запрещено. Название должно быть осмысленным

2020-09-10 15:20 UTC, AlexMasterov commented on src/view/event-edit.js
> +      element.querySelector(`.event__favorite-checkbox`).addEventListener(`change`, this._favoriteChangeHandler);
.event__`favorite-checkbox` !== this._`favorite`ChangeHandler

Д4~

2020-09-10 15:20 UTC, AlexMasterov commented on src/view/event-edit.js
> +  static parseDataToPoint(data) {
`data`

Б4

2020-09-10 15:20 UTC, AlexMasterov commented on src/view/filter.js
>  export default class Filter extends AbstractView {
Д3

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/trip.js
> +  _handleModelEvent(updateType, data) {
`data`

Б4

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/point-new.js
> +    const sortTripElement = this._container.querySelector(`.trip-sort`);
sortTrip`Element`

[`Д 6`](https://up.htmlacademy.ru/ecmascript/12/criteries#d6)
> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, **то это правило работает везде**

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/filter.js
> +export default class Filter {
Д3

2020-09-10 15:20 UTC, AlexMasterov commented on src/model/points.js
> +export default class PointsModel extends Observer {
Д3

2020-09-10 15:20 UTC, AlexMasterov commented on src/model/filter.js
> +export default class Filter extends Observer {
Д3

2020-09-10 15:20 UTC, AlexMasterov commented on src/main.js
> +tripEventButtonComponent.setClickHandler(tripPresenter.createPoint);
`tripPresenter.createPoint`

[`Д 4`](https://up.htmlacademy.ru/ecmascript/12/criteries#d4)
> Из названия обработчика события и функции-коллбэка следует, что это за обработчик

2020-09-10 15:20 UTC, AlexMasterov commented on src/main.js
> +// import {filterNames} from "./mock/filter.js";
Б18

2020-09-10 15:20 UTC, AlexMasterov commented on src/model/points.js
> +    const index = this._points.findIndex((point) => point.id === update.id);
<details>
<summary>PointsModel</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/model/points.js#L27
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/model/points.js#L52
</details>

Д11~

2020-09-10 15:20 UTC, AlexMasterov commented on src/presenter/point-new.js
> +    document.addEventListener(`keydown`, this._handleEscKeyDown);
`keydown` !== this._`handleEscKeyDown`

[`Д 4`](https://up.htmlacademy.ru/ecmascript/12/criteries#d4)
>  Название обработчика строится следующим образом:

> (на каком элементе) + `что случилось` + `Handler`

2020-09-10 15:25 UTC, AlexMasterov requested changes

2020-09-10 15:25 UTC, AlexMasterov commented on src/presenter/point.js
>      this._handleEscKeyDown = this._escKeyDownHandler.bind(this);
Б18

2020-09-11 12:41 UTC, cactusjam commented on src/view/filter.js
>  export default class Filter extends AbstractView {
эм, а что тут не так? 🧐

2020-09-11 12:56 UTC, AlexMasterov commented on src/view/filter.js
>  export default class Filter extends AbstractView {
> эм, а что тут не так?

<details>
<summary>class Filter</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/view/filter.js#L23
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/533e002f27b0541395c238deb445fe64e19664c3/src/view/filter.js#L24
</details>

На защите могут придраться 😟

[`Д 3`](https://up.htmlacademy.ru/ecmascript/12/criteries#d3)
> Название методов и свойств объектов не содержит название объектов

2020-09-11 20:11 UTC, AlexMasterov requested changes
Нужно проверить все названия модулей с классами на соответствие [`Б27`](https://up.htmlacademy.ru/ecmascript/12/criteries#b27), а переменные с их экземплярами (объектами) на [`Д6`](https://up.htmlacademy.ru/ecmascript/12/criteries#d6).

[`Д3`](https://up.htmlacademy.ru/ecmascript/12/criteries#d3) пусть (пере)проверяют на защите 😃

2020-09-11 20:11 UTC, AlexMasterov commented on src/presenter/trip.js
> +export default class TripPresenter {
`TripPresenter` !== presenter/`trip`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/presenter/trip.js
> +    remove(this._sortComponent);
_eventMessageNoEvents`View`
_sort`Component`

Нет единообразия в именование компонентов.

[`Д 6`](https://up.htmlacademy.ru/ecmascript/12/criteries#d6)
> Используется единый стиль именования переменных

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/abstract.js
> +export default class AbstractView {
`AbstractView` !== view/`abstract`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/add-event-button.js
> +export default class AddEventButtonView extends AbstractView {
`AddEventButtonView` !== view/`add-event-button`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/event-edit.js
> +export default class EventEditView extends SmartView {
`EventEditView` !== view/`event-edit`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/event-message.js
> +export default class EventMessageView extends AbstractView {
`EventMessageView` !== view/`event-message`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/filter.js
> +export default class FilterView extends AbstractView {
`FilterView` !== src/view/`filter`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/smart.js
> +export default class SmartView extends AbstractView {
`SmartView` !== view/`smart`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/view/sort.js
> +export default class SortView extends AbstractView {
`SortView` !== src/view/`sort`.js

Б27

2020-09-11 20:11 UTC, AlexMasterov commented on src/main.js
> +const tripPresenter = new TripPresenter(siteMainElement, pointsModel, filterModel);
siteMain`Element`

Д6

2020-09-11 20:41 UTC, cactusjam commented on src/model/filter.js
> +export default class FilterModel extends Observer {
т.е тут будет просто Filter?

2020-09-11 20:45 UTC, AlexMasterov commented on src/model/filter.js
> +export default class FilterModel extends Observer {
> т.е тут будет просто Filter?


См. пример в критерии:
> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2020-09-11 20:46 UTC, cactusjam commented on src/presenter/filter.js
> +export default class FilterPresenter {
и тут тоже просто Filter?

2020-09-12 17:36 UTC, AlexMasterov commented
👍

2020-09-12 17:37 UTC, merged