Module7 task2
htmlacademy-ecmascript/1033161-big-trip-12 pull request #12
Opened 2020-09-15 12:07 UTC by cactusjam

2020-09-15 12:11 UTC, cactusjam commented
Из тз так и не поняла, если мы находимся в Stats, то при нажатии New Event нас должно перекидывать в раздел Table или форма создания отображается находясь и в статистике?

2020-09-15 18:50 UTC, AlexMasterov requested changes

2020-09-15 18:50 UTC, AlexMasterov commented on src/view/statistics.js
> +      chartData[point.type].count++;
<details>
<summary>view/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/66760d3bc6d4a7fe775500d3b5f4a0587c7383fe/src/view/statistics.js#L60-L65
</details>

**4 x** `chartData[point.type]` 😟

2020-09-15 18:50 UTC, AlexMasterov commented on src/view/statistics.js
> +        count: COUNT,
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/66760d3bc6d4a7fe775500d3b5f4a0587c7383fe/src/view/statistics.js#L8

😕

2020-09-15 18:50 UTC, AlexMasterov commented on src/view/statistics.js
> +        groupType: TRANSFER_TYPES.includes(point.type)
[Array.p.`includes`](https://beta.developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) 🤔

Б34~

<details>
<summary>Подскажи, что лучше сделать</summary>

См. [`Set`](https://beta.developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set):

```js
const transportTypeSet = new Set(TRANSFER_TYPES);
```
`createChartData`
```diff
- groupType: TRANSFER_TYPES.includes(point.type)
+ isTransferType: transportTypeSet.has(point.type)
```
</details>

2020-09-15 18:50 UTC, AlexMasterov commented on src/view/trip-controls.js
> +    const newActiveMenuItem = this.getElement().querySelector(`[data-value=${tabsItem}]`);
<details>
<summary>setMenuItem</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/66760d3bc6d4a7fe775500d3b5f4a0587c7383fe/src/view/trip-controls.js#L27
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/66760d3bc6d4a7fe775500d3b5f4a0587c7383fe/src/view/trip-controls.js#L35
</details>

**2 x** `this.getElement()` 😟

2020-09-15 18:50 UTC, AlexMasterov commented on src/view/trip-controls.js
> +    this._callback.menuClick(evt.target.getAttribute(`data-value`));
`.getAttribute` 😕

Д7

2020-09-15 18:50 UTC, AlexMasterov commented on src/constants.js
> +const PointTypeOfIcon = {
~Б7~
```diff
- const PointTypeOfIcon = 
+ const pointTypeToIcon = 
```

> Словарь !== Перечисление (и не "константа")

2020-09-15 18:50 UTC, AlexMasterov commented on src/view/event-add-button.js
> +  setMenuItem(buttonShouldBeActive) {
🤔

```diff
- setMenuItem(buttonShouldBeActive) {
+ setDisabled(value) {
```

2020-09-15 19:00 UTC, AlexMasterov requested changes

2020-09-15 19:04 UTC, AlexMasterov requested changes

2020-09-15 19:04 UTC, AlexMasterov commented on src/main.js
> +      tripComponent.createPoint(newPointFormOpenedHandler);
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/93253184-350b1180-f79f-11ea-863a-b3c5d9d16ad0.png)

</details>

См. ТЗ:
> Одновременно может быть открыта только одна форма создания/редактирования

> Нажатие на кнопку «New Event» закрывает открытую форму редактирования точки маршрута, если таковая была. Изменения при закрытии не сохраняются

Нужно доработать.

2020-09-15 19:07 UTC, AlexMasterov commented
> Из тз так и не поняла, если мы находимся в Stats, то при нажатии New Event нас должно перекидывать в раздел Table или форма создания отображается находясь и в статистике?

Не важно, уже есть проекты с защиты с разным поведением. Предлагаю оставить, как сейчас 😃

2020-09-15 21:16 UTC, AlexMasterov commented on src/view/statistics.js
> +      chartData[point.type].duration += getHourDuration(point.startDate, point.endDate);
```diff
- chartData[point.type].duration += getHourDuration(point.startDate, point.endDate);
+ chartData[point.type].duration += point.endDate - point.startDate;
```

2020-09-16 09:16 UTC, cactusjam commented
> > Из тз так и не поняла, если мы находимся в Stats, то при нажатии New Event нас должно перекидывать в раздел Table или форма создания отображается находясь и в статистике?
> 
> Не важно, уже есть проекты с защиты с разным поведением. Предлагаю оставить, как сейчас 😃

2020-09-16 21:37 UTC, AlexMasterov requested changes

2020-09-16 21:37 UTC, AlexMasterov commented on src/view/event-edit.js
<details>
<summary>Накапливается обработчик на Esc</summary>

![image](https://user-images.githubusercontent.com/700213/93392936-4b39d000-f87a-11ea-8ac8-8b80d0abb8b7.png)
![image](https://user-images.githubusercontent.com/700213/93392982-5db40980-f87a-11ea-9575-102e504bab39.png)
![image](https://user-images.githubusercontent.com/700213/93393056-7a504180-f87a-11ea-861e-969b6b829f6e.png)

</details>

Не удаляются обработчики для `.document` с `Esc`.
При открытии новой формы редактирования или создания новой точки продолжают накапливаться.

[`Б 36`](https://up.htmlacademy.ru/ecmascript/12/criteries#b36)
> Обработчики события добавляются и удаляются своевременно

Нужно разобраться и доработать.

2020-09-16 21:37 UTC, AlexMasterov commented on src/view/statistics.js
> +const transferTypeSet = new Set(TRANSFER_TYPES);
`transferTypeSet`

[`Б 14`](https://up.htmlacademy.ru/ecmascript/12/criteries#b14)
> Код всех JS-файлов соотвествует рекомендованной структуре

> 2. Объявление констант
> 3. **Объявление переменных**

> Перечисления считаются константами

2020-09-16 21:37 UTC, AlexMasterov commented on src/view/statistics.js
> +        groupType: transferTypeSet.has(point.type)
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/967e3ae483c790d6880649b8a9a129cecc878e89/src/view/statistics.js#L71-L73
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/967e3ae483c790d6880649b8a9a129cecc878e89/src/view/statistics.js#L202

Зачем так сложно 🤔

```diff
- groupType: transferTypeSet.has(point.type) 
+ isTransferType: transferTypeSet.has(point.type)
```
```diff
- filter((item) => item.groupType === TRANSFER_TYPES)
+ filter(({isTransferType}) => isTransferType) 
```

2020-09-16 21:37 UTC, AlexMasterov commented on src/view/trip-controls.js
> +      || evt.target.classList.contains(`trip-tabs__btn--active`)) {
Почему не переиспользуется `currentActive` (= `evt.target`)?

Предположу, что из-за названия:

```js
const target = evt.target;

if (target.tagName !== `A` // ...
```

2020-09-16 21:37 UTC, AlexMasterov commented on src/view/event-edit.js
>        element.querySelector(`.event__favorite-checkbox`).addEventListener(`change`, this._favoriteCheckboxClickHandler);
`change` !== _favoriteCheckbox`Click`Handler

Д4

2020-09-16 21:37 UTC, AlexMasterov commented on src/presenter/point-new.js
>  export default class PointNew {
<details>
<summary>console</summary>

```
event-edit.js:310 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at EventEdit.setRollDownButtonClickHandler (event-edit.js:310)
    at EventEdit.restoreHandlers (event-edit.js:342)
    at EventEdit.updateElement (smart.js:34)
    at EventEdit.updateData (smart.js:23)
    at EventEdit._destinationChangeHandler (event-edit.js:283)
```
</details>

Б2

Если в форме создание новой точки маршрута выбрать тип или направление, то выбрасывается исключение (ошибка). 

Нужно разобраться и исправить.

2020-09-16 21:37 UTC, AlexMasterov commented on src/presenter/filter.js
> +      [FilterType.PAST]: filter[FilterType.PAST](points).length !== 0,
<details>
<summary>init</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/967e3ae483c790d6880649b8a9a129cecc878e89/src/presenter/filter.js#L26-L30
</details>

Б34~, Д24~

Задача решается за _один_ цикл (и "правильным" методом массива), без создания двух временных массивов.

2020-09-16 21:37 UTC, AlexMasterov commented on src/utils/filter.js
> +const filter = {
```diff
- const filter = {
+ const filterTypeToPoints = {
```

2020-09-16 21:37 UTC, AlexMasterov commented on src/utils/filter.js
>      return moment(point.startDate).isAfter(new Date(), `day`);
`new Date()` создается новый для _каждого_ `point` 🤔

Получение текущей даты требует системного вызова к ОС, что является [побочным эффектом](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B1%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), который усложняет тестирование функции:

> Если вызвать функцию с побочным эффектом дважды с одним и тем же набором значений входных аргументов, может случиться так, что в качестве результата будут возвращены разные значения

Поэтому дату лучше передать через аргумент.

> `moment` здесь тоже не нужен

2020-09-16 21:52 UTC, AlexMasterov requested changes

2020-09-16 21:52 UTC, AlexMasterov commented on src/view/filters.js
> +    this._currentFilters = currentFilters;
<details>
<summary>Filters</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/967e3ae483c790d6880649b8a9a129cecc878e89/src/view/filters.js#L23
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/967e3ae483c790d6880649b8a9a129cecc878e89/src/view/filters.js#L27
</details>

Пресловутый Д3~ 😟

2020-09-17 12:42 UTC, cactusjam commented on src/presenter/filter.js
> +      [FilterType.PAST]: filter[FilterType.PAST](points).length !== 0,
some так и не сообразила как тут прикрутить.

такой вариант подойдет? 
![Screenshot_2](https://user-images.githubusercontent.com/58633055/93471657-51709080-f8fc-11ea-9eaf-79aea3e41bad.jpg)

2020-09-18 08:36 UTC, AlexMasterov approved these changes

2020-09-18 08:47 UTC, AlexMasterov commented on src/presenter/filter.js
> +      [FilterType.PAST]: filter[FilterType.PAST](points).length !== 0,
Формально это также нарушает критерий, но слепую защиту может пройти 😃

Продолжим в след. задание.

2020-09-18 08:47 UTC, merged

2020-09-18 10:48 UTC, cactusjam commented on src/presenter/filter.js
> +      [FilterType.PAST]: filter[FilterType.PAST](points).length !== 0,
да я уже и не рассчитываю успеть до конца защиты 😃

2020-09-18 11:12 UTC, cactusjam commented on src/presenter/point-new.js
> +    this._component = new EventEditView(this._attributes, this._destinations, {isAddMode: true}, {isNewPoint: true}, {isNewEvent: true});
правила в одном месте и не поправила в другом:((