Module5 task2
htmlacademy-ecmascript/1033161-big-trip-12 pull request #8
Opened 2020-08-27 20:47 UTC by cactusjam

2020-08-27 21:36 UTC, AlexMasterov requested changes

2020-08-27 21:36 UTC, AlexMasterov commented on src/presenter/trip.js
> +      this._sortComponent.getElement().querySelector(`.trip-sort__item--day`).innerHTML = ``;
<details>
<summary>presenter/trip.js</summary>

https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/964a0d8e410aebf63dc8087f68ab0344140abfd4/src/presenter/trip.js#L56
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/964a0d8e410aebf63dc8087f68ab0344140abfd4/src/presenter/trip.js#L58
</details>

Д26

Прямая работа с элементом компонента нарушает его инкапсуляцию.

> Нужно исправить в этом или в след. заданиях

2020-08-27 21:36 UTC, AlexMasterov commented on src/utils/utils.js
> +  const durationB = new Date(eventB.endDate) - new Date(eventB.startDate);
```js
eventA.endDate instanceof Date   // true
eventA.startDate instanceof Date // true
```
```js
(eventB.endDate - eventB.startDate) - (eventA.endDate - eventA.startDate)
```

2020-08-27 21:36 UTC, AlexMasterov commented on src/view/sort.js
> +  setSortTypeChangeHandler(callback) {
`Sort`.set`Sort`TypeChangeHandler

Д3~

2020-08-27 21:36 UTC, AlexMasterov commented on src/view/sort.js
> +  _sortTypeChangeHandler(evt) {
`Sort`._`sort`TypeChangeHandler

Д3~

2020-08-27 21:36 UTC, AlexMasterov commented on src/presenter/trip.js
> +    this._tripDaysComponent._element.innerHTML = ``;
```js
._element.innerHTML = ``;
```

Д26

Обращение с приватному свойству, прямая работа с элементом компонента.

2020-08-27 21:36 UTC, AlexMasterov commented on src/view/sort.js
> +        <input id="sort-event" class="trip-sort__input  visually-hidden" type="radio" name="trip-sort" value="sort-event" checked data-sort-type="${SortType.DEFAULT}">
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/964a0d8e410aebf63dc8087f68ab0344140abfd4/src/view/sort.js#L59

Зачем `data-*`, когда есть `input` 🤔

```diff
- <input id="sort-event" class="trip-sort__input  visually-hidden" type="radio" name="trip-sort" value="sort-event" checked data-sort-type="${SortType.DEFAULT}">
+ <input id="sort-event" class="trip-sort__input  visually-hidden" type="radio" name="trip-sort" value="${SortType.DEFAULT}">
```
```js
evt.target.value // SortType.DEFAULT
```

2020-08-27 21:36 UTC, AlexMasterov commented on src/view/trip-day.js
>    constructor(counter, startDate) {
https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/964a0d8e410aebf63dc8087f68ab0344140abfd4/src/view/trip-day.js#L32-L34

Желательно что-то вроде этого:

```diff
- constructor(counter, startDate) {
+ constructor(startDate = new Date(), counter = 0) {
```
```js
if (counter < 1) { ... }
if (counter > 0) { ... }
if (counter === 0) { ... }
```

2020-08-27 21:37 UTC, merged

2020-08-28 18:35 UTC, cactusjam commented on src/view/sort.js
> +  _sortTypeChangeHandler(evt) {
с неймингом поняла, а что кроется под замечанием "Д3~"? 😃

2020-08-28 18:37 UTC, AlexMasterov commented on src/view/sort.js
> +  _sortTypeChangeHandler(evt) {
_Могут_ придраться.