Module6 task1
htmlacademy-ecmascript/1033161-big-trip-12 pull request #9
Opened 2020-09-03 16:28 UTC by cactusjam

2020-09-03 16:55 UTC, cactusjam commented
![sticker](https://user-images.githubusercontent.com/58633055/92144411-583cd500-ee1f-11ea-88e7-80697db35837.png)

2020-09-04 00:55 UTC, AlexMasterov requested changes

2020-09-04 00:55 UTC, AlexMasterov commented on src/view/event-edit.js
<details>
<summary>view/event-edit.js</summary>

![image](https://user-images.githubusercontent.com/700213/92186778-8abaf200-ee60-11ea-98bc-483488d47ac4.png)


https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/2062aa39f8e340f1c50549cb23aec1a369c5569e/src/view/event-edit.js#L76
</details>

В режиме редактирования (созданной) точки маршрута вместо кнопки `Cancel` должна быть кнопка `Delete`.

См. [markup/`edit-event.html`](https://github.com/htmlacademy-ecmascript/1033161-big-trip-12/blob/2062aa39f8e340f1c50549cb23aec1a369c5569e/markup/edit-event.html#L247).

2020-09-04 11:54 UTC, cactusjam commented on src/presenter/trip.js
>    constructor(eventsContainer, renderBlock) {
с renderBlock  непонятно.. Те я могу сделать export этой функции напрямую из main, где он хранится? 
просто насколько я поняла, что это неверный подход 😩

2020-09-04 12:02 UTC, cactusjam commented on src/presenter/trip.js
>    constructor(eventsContainer, renderBlock) {
рубрику глупых вопросов считаю открытой)

2020-09-04 12:06 UTC, AlexMasterov commented on src/presenter/trip.js
>    constructor(eventsContainer, renderBlock) {
> я могу сделать export этой функции напрямую из main, где он хранится?

Технически так сделать можно, но это создаст циклическую зависимость между модулями.

Можешь просто перенести функцию в модуль `presenter/trip.js` или создать для неё отдельный `utils/trip.js`. Также можно попробовать от неё избавиться, упростив код 😃

2020-09-05 11:55 UTC, AlexMasterov commented
👍

2020-09-05 11:55 UTC, merged